<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<html>
	<head>
		<!-- @todo: add magento header and footer -->
	</head>
	<body>
		<?php
		$qrResponse = $block->getTransactionQR();
		if (isset($qrResponse['error'])) {
			echo $qrResponse['error'];
			//@todo show back button with a message
		} else {
			$tranID = $qrResponse['TranID'];
			$pictureURL = $qrResponse['PictureURL'];
			$returnText = $qrResponse['ReturnText'];
			switch ($qrResponse['Flag']) {
				case -1:
				case 10:
					echo __($returnText);
					//@todo show back button with a message
					break;
				case 2:
					echo __("Your order has been placed! Scan the QR with your sKash app to complete the payment.");
					echo "<img src='$pictureURL' alt='sKash QR code' title='sKash QR code'/>";
					break;
			}
		}
		?>
		<script>
		    // document.getElementById('skash_form').submit();
		</script>
	</body>
</html>
