<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

$qrResponse = $block->getTransactionQR();

if (isset($qrResponse['error'])) {
	?>
	<div>
		<h2>
			<?php echo __("An error occured!"); ?>
		</h2>
		<p><?php echo __('Try again or choose another payment method.'); ?></p>
		<p>
			<?php echo __('Click <a href="%1">here</a> to go back to checkout page.',
	            $block->escapeUrl($block->getCheckoutUrl())); ?>
		</p>
		<p>
			<?php echo __('Or click <a href="%1">here</a> to continue shopping.',
				$block->escapeUrl($block->getContinueShoppingUrl())); ?>
		</p>
	</div>
	<?php
} else {
	$tranID = $qrResponse['TranID'];
	$pictureURL = $qrResponse['PictureURL'];
	$returnText = $qrResponse['ReturnText'];
	switch ($qrResponse['Flag']) {
		case $block->PAYMENT_STATUS_ERROR:
		case $block->PAYMENT_STATUS_INVALID_DATA:
			echo __($returnText);
			//@todo show back button with a message
			break;
		case $block->PAYMENT_STATUS_SUCCESS:
			?>
			<div id="skash_qr_response" data-status-check="<?php echo $block->getStatusChangeUrl() . 'status_changed?order_id=1' . $tranID; ?>">
				<h2>
					<?php echo __("Your order has been placed!"); ?>
				</h2>
				<p>
					<?php echo __("Scan the QR with your sKash app to complete the payment."); ?>
				</p>
				<p>
					<?php echo "<img id='skash_qr_image' src='$pictureURL' alt='sKash QR code' title='sKash QR code'/>"; ?>
				</p>
			</div>
			<?php
			break;
	}
}
?>
<script>
	// @todo: move js to separate file https://magently.com/blog/introduction-knockout-js-magento-2/
require([
    'jquery'  // the alias for "mage/accordion"
], function ($) {

    $(function () { // to ensure that code evaluates on page load
		console.log('here -----------------');
		var url = $('#skash_qr_response').data('status-check');
		console.log(url);
        $(document).ready(function() {
            $.ajax({
                url: url,
                type: "GET",
                dataType: 'json'
            }).done(function (data) {
				console.log('success -----------------');
				console.log(data);
                // $('#test').removeClass('hideme');
                // var html = template('#test', {posts:data});
                // $('#test').html(html);
            });
        });
    });

});
</script>

<style>
@media (min-width: 978px) {
	#skash_qr_image {
		max-width: 50%;
		height: auto;
	}
}
</style>
